api_platform:
    enable_swagger_ui: false
    enable_re_doc: false
    formats:
        json: [ 'application/json' ]
        jsonld: [ 'application/ld+json' ]
    patch_formats:
        json: [ 'application/json' ]
